# Generated by Django 4.1.2 on 2022-11-16 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=1, max_digits=1)),
                ('cuisineType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=1, max_digits=1)),
                ('description', models.CharField(max_length=100)),
                ('restuarant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mealreviews.restaurant')),
            ],
            options={
                'db_table': 'Dish',
            },
        ),
    ]
