# Generated by Django 4.1.2 on 2022-11-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealreviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
