# Generated by Django 4.1.2 on 2022-12-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealreviews', '0002_alter_restaurant_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
