# Generated by Django 4.1.2 on 2022-12-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealreviews', '0004_alter_dish_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealreviews.restaurant'),
        ),
    ]
