# Generated by Django 4.1.2 on 2022-12-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealreviews', '0005_alter_dish_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='score',
        ),
    ]
